version: '3.8'
services:
  app:
    restart: unless-stopped
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node_network

  web:
    image: nwtgck/nginx-http3
    restart: unless-stopped
    build: ./web
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/usr/local/nginx/conf/nginx.conf
      - ./web/ssl/server.crt:/etc/ssl/certs/server.crt
      - ./web/ssl/server.key:/etc/ssl/private/server.key
    networks:
      - node_network

networks:
  node_network:
